// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhfehknwjrsgclhzwshc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZmVoa253anJzZ2NsaHp3c2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDIyMTMsImV4cCI6MjA2MzgxODIxM30.C_uaml785tp6QfqXA5NIE553WyHxcs1G3nOj3zOzgsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);